### ISSUE TITLE
Test Results upload to TFS

### ISSUE THREAD

**Issue by frozenskys** [cake-build/cake-vso#29]
Anyone interested in having cake-vso have an option to upload test results and coverage into TFS without having to use another build step? I'm looking at developing a basic version of this for our internal process and was wondering if it would be helpful for others.

**Comment by gep13** [comment]
@frozenskys apologies that no-one ever got back to you about this issue, it seems like it has fallen through the cracks.  I am going to go ahead and close this out, but if you wanted to continue with this, please feel free to respond to the issue.
