### ISSUE TITLE
Cake.ps1 doesn't download the latest nuget

### ISSUE THREAD

**Issue by fleed** [cake-build/cake-vso#32]
Cake.ps1 is downloading nuget.exe using the address `https://nuget.org/nuget.exe`, which returns an old version (`2.8.60717.93`).

The `build.ps1` script that it is added using the `Visual Studio Extension` bootstraps downloading from `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`, which returns the latest version.

Shouldn't Cake.ps1 download the latest version, unless differently configured (see [this issue](https://github.com/cake-build/cake-vso/issues/31))?

**Comment by rj-cooper** [comment]
@fleed this should be fixed as part of PR https://github.com/cake-build/cake-vso/pull/30

**Comment by fleed** [comment]
@frozenskys thanks, that looks exactly what's needed and I can close this issue.
