### ISSUE TITLE
Break the output of a single cake build step into multiple build output sections

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake-vso#33]
When you convert TFS build steps to Cake, you end up removing individual steps in TFS and replacing them with a single Cake step.

The single build step is nice but I don't want to give up the ability to see timings and sections of the build output for restoring nuget packages, for msbuild, for testing, and any other Cake targets.

**Comment by gep13** [comment]
Issue moved to [cake-build/cake #1340](https://github.com/cake-build/cake/issues/1340) via [**ZenHub**](https://www.zenhub.com/)
