### ISSUE TITLE
Old nuget.exe version

### ISSUE THREAD

**Issue by trailmax** [cake-build/cake-vso#34]
In my VSTS build I've encountered a build error:

>Executing: "D:/a/1/s/tools/nuget.exe" install "xunit.runner.console" -OutputDirectory "D:/a/1/s/tools" -Source "https://packages.nuget.org/api/v2" -ExcludeVersion -NonInteractive -NoCache
##[error]The 'xunit.runner.console 2.2.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.

So nuget.exe is version. And it is provided by the plugin, not VSTS server - see the path - it is taking `../tools/nuget.exe`. And looking on the plugin source, this [line is probably the cause](https://github.com/cake-build/cake-vso/blob/develop/Task/Cake.ps1#L44). It downloads nuget.exe from `https://nuget.org/nuget.exe` and examining that file it is of version 2.8.6. 

I'm unsure if this is what nuget.org/nuget.exe had all the time, but this URL seems to be inconsistent with [default `build.ps1`](https://github.com/cake-build/cake/blob/develop/build.ps1#L38), where nuget.exe is downloaded from `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`

I'd quickly jump to do a PR to update the url, but there is already an issue for #4 that talks about a broader picture. So what should we do?

**Comment by trailmax** [comment]
Oh.. I see there is work in progress for this already: https://github.com/cake-build/cake-vso/pull/30

**Comment by agc93** [comment]
Similar issue to #31 

Fixed by #30
