### ISSUE TITLE
Restore modules for parity with bootstrapper

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake-vso#37]
The Cake extension 0.3.0 does not restore modules. It should handle restoring `tools\Modules\packages.config` just like it already does with `tools\packages.config`.

https://github.com/agc93/Cake.BuildSystems.Module/blob/master/README.md#using-the-latest-bootstrapper recommends using the convention of `tools\Modules\packages.config`, just like we've always done with `tools\packages.config`. 

The workaround is to not use the Cake VSO extension and instead run `build.ps1` in a PowerShell task with the working directory set to the directory containing `build.ps1`.

(Similar to https://github.com/cake-build/cake-vso/issues/19)

**Comment by agc93** [comment]
Thanks for the report @jnm2 I'd been thinking about this lately as well for obvious reasons!

As an aside, a "better" workaround would be to add a NuGet Installer step immediately before the Cake step and point it at your `tools/Modules/packages.config` folder. 

![screenshot from 2017-04-28 23-36-08](https://cloud.githubusercontent.com/assets/1369269/25531100/f3cbb5c8-2c6b-11e7-85a7-28d93e80d6fe.png)

I'll look into fixing this properly very soon!

**Comment by agc93** [comment]
I've updated this issue to be specific to module restore (as per @gep13's comments), as this will be resolved by #41 

I've created a separate issue for the handling of the addins restore, which we won't be adding at this time, in #42 .

**Comment by jnm2** [comment]
Very cool! When should I look for the next release?
