### ISSUE TITLE
Support for "Queue with Diagnostics"

### ISSUE THREAD

**Issue by richardgavel** [cake-build/cake-vso#46]
In Azure DevOps, you can queue a build or "Queue with diagnostics", which sets a variable "system.debug" to "true". It would be nice if we could define 2 different verbosity levels, one for default and one for when when "with diagnostics" is used. Right now, with YAML based builds, to do an elevated logging level, I have to check in a YAML change.

**Comment by gep13** [comment]
@richardgavel we have recently released a new cross platform version of the Cake Task, and I would like to tackle this task next.  Do you happen to know of any documentation around how this works under the hood?  Thanks
