### ISSUE TITLE
Team Services extension for cake cant find nuget.exe

### ISSUE THREAD

**Issue by gep13** [cake-build/cake-vso#5]
@robgha01 commented on [Mon Jun 20 2016](https://github.com/cake-build/cake/issues/993)

Hi

i get this in a team service build i just created for the first time with "https://marketplace.visualstudio.com/items?itemName=cake-build.cake"

but it throws this error

> ---
> 
> Starting task: Cake
> ---
> 
> Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.101.1\tasks\Cake\0.1.6\Cake.ps1
> Creating tools directory...
> Installing Cake...
> Installing 'Cake 0.13.0'.
> Successfully installed 'Cake 0.13.0'.
> C:\a\1\s\tools\Cake\Cake.exe "C:\a\1\s\Build\build.module.cake" -target="Build-Nuget" -verbosity="Diagnostic" -targetOutput="C:\a\1\a"
> Module directory does not exist.
> Analyzing build script...
> Analyzing C:/a/1/s/Build/build.module.cake...
> Processing build script...
> Installing tools...
> Creating directory C:/a/1/s/Build/tools
> Installing NuGet package NUnit.ConsoleRunner...
> **Error: Cake.Core.CakeException: Could not locate nuget.exe.
> at Cake.Core.IO.NuGet.NuGetToolResolver.ResolvePath()
> at Cake.NuGet.NuGetPackageInstaller.GetNuGetPath()
> at Cake.NuGet.NuGetPackageInstaller.Install(PackageReference package, PackageType type, DirectoryPath path)
> at Cake.Core.Scripting.ScriptProcessor.InstallTools(ScriptAnalyzerResult analyzerResult, DirectoryPath installPath)
> at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
> at Cake.Commands.BuildCommand.Execute(CakeOptions options)
> at Cake.CakeApplication.Run(CakeOptions options)
> at Cake.Program.Main()
> System.Exception: Unexpected exit code 1 returned from tool Cake.exe
> at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeToolCmdlet.ProcessRecord()
> at System.Management.Automation.CommandProcessor.ProcessRecord()**
> ---
> 
> Finishing task: Cake
> ---

---

@robgha01 commented on [Tue Jun 21 2016](https://github.com/cake-build/cake/issues/993#issuecomment-227423232)

Ok, i found way it dide not work with the cake extension for team services... its not installing nuget if its not found in the tools folder but it do download and install cake.exe this must be a bugg... i managed to patch it with the following powershell that i run before the extension `New-Item -ItemType Directory -Force -Path "./Build/tools/";
Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile "./Build/tools/nuget.exe"`

**Comment by gep13** [comment]
@robgha01 based on the Cake.ps1 file that you can find here:  https://github.com/cake-build/cake-vso/blob/develop/Task/Cake.ps1#L34 The only reason that the nuget.exe wouldn't be downloaded is if it already exists.

@patriksvensson any thoughts on why this would happen?

**Comment by gep13** [comment]
Full gist of the build output can be found here: https://gist.github.com/robgha01/9261fcfccf8201b2d03532866ae6ce1c

**Comment by gep13** [comment]
@robgha01 can you confirm the folder structure that you are using?  Can you provide a screenshot?  I think I might know what the issue is.

**Comment by robgha01** [comment]
@gep13  this is the folder structure i use for my projects ![image](https://cloud.githubusercontent.com/assets/362726/16229559/9db985e6-37bd-11e6-8d54-4e33aa2df170.png)

and the build folder content is
![image](https://cloud.githubusercontent.com/assets/362726/16229574/b81d66fa-37bd-11e6-8e8d-cda06c015786.png)

**Comment by robgha01** [comment]
the content of build.module.cake if needed 
[build.module.cake.zip](https://github.com/cake-build/cake-vso/files/325585/build.module.cake.zip)

i call it like this 
![image](https://cloud.githubusercontent.com/assets/362726/16229699/30ba015e-37be-11e6-9f85-69b71b1fa749.png)

**Comment by gep13** [comment]
@robgha01 ok, I think I see what the problem is, but also, the extension perhaps needs to be altered to handle it, but not sure how it would need to be changed.

There is an assumption that the build.cake file is at the root of the repository, or at least, it should be at the same location as the tools folder that is created as part of the bootstrapper script that the extension is using, i.e. the Cake.ps1 file.

What is happening is this...

the Cake.ps1 file is creating a tools folder at the root of your repository, and in there it is putting the nuget.exe.  Then, when your build.cake file is executing, it is creating another tools folder at the same location as the build.cake file.  This tools folder doesn't have the nuget.exe in it :cry: 

There is likely "something" that we can do to work around this for you, but for testing purposes, could you try putting the build script at the root of the repository?

**Comment by devlead** [comment]
@gep13 currently nuget.exe path isn't set to `$ENV:NUGET_EXE = $NUGET_EXE` or adding `$ENV:path` in [Cake.ps1](https://github.com/cake-build/cake-vso/blob/develop/Task/Cake.ps1), could be that something has changed in VSTS.
Also linked used might be depreciated, should use one of those avail [here](https://dist.nuget.org/index.html)

**Comment by robgha01** [comment]
@gep13 yes it seams to work if i have the cake file in the root howerver i get other errors but its not strange as i dide not alter the "../" root variable but it dide find nuget this time. :/ is it possilbe to make this work with the build map witout having to manualy create a powershell script to download the nuget.exe ?

**Comment by gep13** [comment]
> @robgha01 said...
> is it possilbe to make this work with the build map witout having to manualy create a powershell script to download the nuget.exe ?

Yes, that is certainly the intention.  I definitely think some work is required within the extension to make it work the way that it is intended.  Perhaps the suggestions that @devlead has made can be combined to make the solution better.

**Comment by gep13** [comment]
@devlead could we make use of a cake.config file to specify the location of the tools folder as one level higher in the build folder hierarchy?

**Comment by robgha01** [comment]
@gep13 well it sounds like it could be done like that im however very new with the whole cake build project so i only know a little about it :)

**Comment by gep13** [comment]
@robgha01 ok, give this a try...

Put the build.cake file back where it was.  Create a new file called cake.config, and put the following into it:

```
; The configuration file for Cake.

[Paths]
Tools=./../tools
```

And try running it again, without the extra *.ps1 file, and let us know how you get on.

This was based on the documentation here:

http://cakebuild.net/docs/fundamentals/default-configuration-values

**Comment by gep13** [comment]
@robgha01 _NOTE:_ the cake.config should be placed beside the build.cake file.

**Comment by robgha01** [comment]
@gep13 it dide not work here is the log i got https://gist.github.com/robgha01/2681e5490583d79307da9d4f61e4c92b

**Comment by gep13** [comment]
@robgha01 ok, I am going to need to look at this later, need to get back to work work just now.  I will try to look at this later tonight.

**Comment by robgha01** [comment]
@gep13 ok, :+1:

**Comment by patriksvensson** [comment]
@robgha01 Can you post the output of the build with diagnostic verbosity?

**Comment by robgha01** [comment]
@patriksvensson here is the gist https://gist.github.com/robgha01/6ee451bb295c7cd668ea03759efae8b4

and settings i used
![image](https://cloud.githubusercontent.com/assets/362726/16230944/2fe19944-37c4-11e6-966a-7e457c49fdfa.png)

**Comment by patriksvensson** [comment]
@robgha01 My mistake. Read the log wrong. Thanks for clearing this up :smile:

**Comment by robgha01** [comment]
@patriksvensson ok no problem :+1:

**Comment by gep13** [comment]
@robgha01 just to keep you up to date on this one...

Myself @patriksvensson and @devlead were looking into this issue last night.  We have found at least one issue with how Cake is looking for the cake.config file which prevented the initial suggestion from working, and a PR has been raised here: https://github.com/cake-build/cake/pull/1003 to correct that.  In addition, we think that there are some improvements that need to be made to the extension itself to handle this situation a bit better.   We will also be looking into getting an update pushed out for that as well.

**Comment by robgha01** [comment]
@patriksvensson @devlead Ok, that sounds great :) :+1:

**Comment by patriksvensson** [comment]
I've spoken with @gep13 and we have a solution to the problem. By providing the bootstrapper's tool path via the `--paths_tools` argument, Cake will always look in the same place for tools.

**Comment by robgha01** [comment]
@patriksvensson ok, that sounds great will this override be created for the team service cake extension to ? :+1:

**Comment by patriksvensson** [comment]
@robgha01 This override will only be added to the team service cake extension.

**Comment by gep13** [comment]
@robgha01 I have just pushed the new version of this extension, version 0.1.7, can you please give it a try, and let us know how you get on? Thanks!

**Comment by robgha01** [comment]
@gep13 i have to wait as i ran out of build time.

**Comment by gep13** [comment]
> @robgha01 said....
> @gep13 i have to wait as i ran out of build time.

Not a problem at all, just when you have time.
