### ISSUE TITLE
TLS issue

### ISSUE THREAD

**Issue by medekjak** [cake-build/cake-vso#67]
### What You Are Seeing?
There is an issue in the TFS 2015 plugin 0..4.4. Thanks

2020-06-16T07:41:05.3126623Z ##[section]Starting: Cake 
2020-06-16T07:41:05.3316762Z ==============================================================================
2020-06-16T07:41:05.3316762Z Task         : Cake
2020-06-16T07:41:05.3316762Z Description  : Build with Cake
2020-06-16T07:41:05.3316762Z Version      : 0.4.4
2020-06-16T07:41:05.3316762Z Author       : Patrik Svensson
2020-06-16T07:41:05.3316762Z Help         : [More Information about Cake](https://cakebuild.net)
2020-06-16T07:41:05.3316762Z ==============================================================================
2020-06-16T07:41:07.4111978Z [error]Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."

**Comment by leszekrogowski** [comment]
I'm experiencing the same problem. It's probably connected with the following notification from [https://www.nuget.org/downloads](https://www.nuget.org/downloads):

" NuGet.org will permanently remove support for TLS 1.0 and 1.1 on June 15th. Please ensure that your systems use TLS 1.2."

Maybe enabling TLS 1.2 on WebClient will resolve the issue.

**Comment by PatrickKalkman** [comment]
Same issue here, having problems since today

**Comment by leszekrogowski** [comment]
One of the workarounds, before getting patch for it, is to add "NuGet Tool Installer" step, which will download NuGet correctly and will add it to PATH, and check "Use the Build Agent NuGet" checkbox in Advanced section of Cake Build step.

**Comment by kapsiR** [comment]
Since there is no explicit selected version in the [script](https://github.com/cake-build/cake-vso/blob/ebc6db3375fae419e38e802be5e3f41579e80a57/Task/Cake.ps1#L58), you can use the following workaround/solution:

Update the default TLS version on the server to allow the operating system to choose the protocol:
[Transport Layer Security (TLS) best practices with the .NET Framework - SystemDefaultTlsVersions](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#systemdefaulttlsversions)
*Note: This also sets `SchUseStrongCrypto`, because it's recommended to use more secure protocols. (default since .NET 4.6)*

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001
```

But be aware, [as stated in the docs](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#configuring-security-via-the-windows-registry):

> Setting registry keys affects all applications on the system. Use this option only if you are in full control of the machine and can control changes to the registry.

**Comment by sundar85** [comment]
Or you can also use these commands as mentioned by Azure DevOps, if you're using self-hosted azure devops agents.

https://devblogs.microsoft.com/devops/azure-devops-services-to-require-tls-1-2/

New-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319' -Name SchUseStrongCrypto -Value 1 -PropertyType 'Dword' -Force | Out-Null 

New-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319' -Name SystemDefaultTlsVersions -Value 1 -PropertyType 'Dword' -Force | Out-Null 

If ([System.Environment]::Is64BitOperatingSystem) { 

  New-ItemProperty -Path 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319' -Name SchUseStrongCrypto -Value 1 -PropertyType 'Dword' -Force | Out-Null 

  New-ItemProperty -Path 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319' -Name SystemDefaultTlsVersions -Value 1 -PropertyType 'Dword' -Force | Out-Null 
}

**Comment by gep13** [comment]
@medekjak @leszekrogowski @PatrickKalkman @kapsiR @sundar85 We have released a new version of this Task, which uses Node execution, rather than PowerShell, and which uses the Cake .Net Global Tool.  Can any of you confirm that this is still an issue using this version?  Thanks

**Comment by kapsiR** [comment]
@gep13 Yes, I can confirm the fix for the new pipeline task version `2.*`.

**Comment by gep13** [comment]
@kapsiR that is great! Thank you for confirming!  I will go ahead and close out this issue.
